#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import json
import os
import re
import time
import sqlite3
import urllib.request
from typing import Any, Dict, List, Optional, Tuple

import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
from peft import PeftModel

from src.spider.load_spider import iter_spider_samples
from src.rag.retrieve import retrieve_schema_context


PROMPT = """You are a Text-to-SQL system.
Write ONE valid SQLite SQL query.

Rules:
- Output SQL ONLY. One statement.
- Use ONLY table/column names from the ALLOWED LIST.
- If a table/column is not in the allowed list, you MUST NOT use it.
- The SQL must start with SELECT or WITH and end with a semicolon.

Schema context:
{schema}

ALLOWED TABLES:
{allowed_tables}

ALLOWED COLUMNS:
{allowed_cols}

Question:
{question}

SQL:
"""

_CODE_FENCE = re.compile(r"```(?:sql)?\s*(.*?)```", flags=re.IGNORECASE | re.DOTALL)

def extract_sql(text: str) -> str:
    t = (text or "").strip()
    m = _CODE_FENCE.search(t)
    if m:
        t = m.group(1).strip()
    m = re.search(r"\b(SELECT|WITH)\b", t, flags=re.IGNORECASE)
    if not m:
        return t.strip()
    t = t[m.start():].strip()
    if ";" in t:
        t = t.split(";", 1)[0].strip() + ";"
    else:
        t = t.rstrip() + ";"
    return t

def is_sql_like(s: str) -> bool:
    s = (s or "").strip().upper()
    return s.startswith("SELECT") or s.startswith("WITH")

def parse_allowed_from_schema(schema_text: str, max_tables: int = 80, max_cols: int = 400) -> Tuple[str, str]:
    tables: List[str] = []
    cols: List[str] = []
    for line in (schema_text or "").splitlines():
        s = line.strip()
        if s.startswith("Table: "):
            tables.append(s.replace("Table: ", "").strip())
        elif s.startswith("Column: "):
            cols.append(s.replace("Column: ", "").strip())
    tables = sorted(set(tables))[:max_tables]
    cols = sorted(set(cols))[:max_cols]
    return ("\n".join(tables) if tables else "(none)",
            "\n".join(cols) if cols else "(none)")

def default_db_path(db_root: str, db_id: str) -> str:
    return os.path.join(db_root, db_id, f"{db_id}.sqlite")

def _sqlite_exec_with_timeout(db_path: str, sql: str, timeout_s: float = 1.0, max_rows: int = 200) -> Tuple[bool, Optional[str], int]:
    if not is_sql_like(sql):
        return (False, "not_sql", 0)
    if not os.path.exists(db_path):
        return (False, f"db_not_found:{db_path}", 0)

    start = time.time()
    conn = sqlite3.connect(db_path)
    try:
        def progress_handler():
            if time.time() - start > timeout_s:
                return 1
            return 0
        conn.set_progress_handler(progress_handler, 10000)

        cur = conn.cursor()
        cur.execute(sql)
        rows = cur.fetchmany(max_rows)
        return (True, None, len(rows))
    except sqlite3.OperationalError as e:
        msg = str(e)
        if "interrupted" in msg.lower():
            return (False, "timeout", 0)
        return (False, msg, 0)
    except Exception as e:
        return (False, str(e), 0)
    finally:
        try:
            conn.close()
        except Exception:
            pass

# -------- DeepSeek (OpenAI-compatible) chat call --------

def call_chat_api(prompt: str, api_key: str, model: str, base_url: str, temperature: float = 0.0) -> str:
    payload = {
        "model": model,
        "messages": [{"role": "user", "content": prompt}],
        "temperature": float(temperature),
    }
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        base_url,
        data=data,
        headers={"Content-Type": "application/json", "Authorization": f"Bearer {api_key}"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=180) as resp:
        out = json.loads(resp.read().decode("utf-8"))
    return out["choices"][0]["message"]["content"].strip()

REPAIR_AGGRESSIVE_PROMPT = """You are a senior Text-to-SQL engineer.
Your job: produce the BEST possible single SQLite query for the Question.

You are given:
- Schema context (tables/columns/fks)
- Allowed tables/columns
- A list of candidate SQLs generated by a base model
- For each candidate: execution status (ok/err) and a small row_count sample

Requirements:
- Output SQL ONLY. One statement ending with semicolon.
- Use ONLY names from the allowed list.
- JOIN only if supported by foreign keys in schema context.
- Prefer an executable SQL. If multiple are executable, prefer the one most likely correct.

Schema context:
{schema}

ALLOWED TABLES:
{allowed_tables}

ALLOWED COLUMNS:
{allowed_cols}

Question:
{question}

CANDIDATES WITH EXECUTION FEEDBACK:
{cands_block}

If previous attempt failed, here's the last error:
{last_error}

BEST SQL:
"""

def format_candidates_for_repair(cands_sql: List[str], exec_infos: List[Dict[str, Any]], max_chars: int = 4000) -> str:
    parts = []
    for i, (sql, info) in enumerate(zip(cands_sql, exec_infos)):
        ok = info.get("ok")
        err = info.get("err")
        rows = info.get("rows")
        parts.append(f"[{i}] ok={ok} rows={rows} err={err}\nSQL: {sql}\n")
    block = "\n".join(parts)
    if len(block) > max_chars:
        block = block[:max_chars] + "\n...(truncated)\n"
    return block

def pick_device() -> str:
    if torch.backends.mps.is_available():
        return "mps"
    return "cpu"


def main():
    ap = argparse.ArgumentParser()

    ap.add_argument("--dev_json", default="data/spider/dev.json")
    ap.add_argument("--bm25_index", default="runs/cache/bm25_schema")
    ap.add_argument("--db_root", default="data/spider/database")

    ap.add_argument("--adapter_dir", required=True)
    ap.add_argument("--base_model", default="google/flan-t5-base")

    ap.add_argument("--out", default="runs/outputs/pred_dev_lora_egs_aggrrepair.jsonl")
    ap.add_argument("--limit", type=int, default=500)

    # RAG
    ap.add_argument("--topk_table", type=int, default=5)
    ap.add_argument("--topk_col", type=int, default=8)
    ap.add_argument("--topk_fk", type=int, default=8)
    ap.add_argument("--schema_char_limit", type=int, default=1800)

    # Generation / exec
    ap.add_argument("--num_candidates", type=int, default=12)
    ap.add_argument("--max_new_tokens", type=int, default=160)
    ap.add_argument("--timeout", type=float, default=1.0)
    ap.add_argument("--max_rows", type=int, default=200)

    # Aggressive repair (always)
    ap.add_argument("--api_key", required=True)
    ap.add_argument("--repair_model", default="deepseek-reasoner")
    ap.add_argument("--base_url", default="https://api.deepseek.com/v1/chat/completions")
    ap.add_argument("--repair_rounds", type=int, default=2)

    args = ap.parse_args()
    os.makedirs(os.path.dirname(args.out), exist_ok=True)

    device = pick_device()
    print("[INFO] device:", device)

    tok = AutoTokenizer.from_pretrained(args.adapter_dir)
    base = AutoModelForSeq2SeqLM.from_pretrained(args.base_model)
    model = PeftModel.from_pretrained(base, args.adapter_dir)
    model.to(device)
    model.eval()

    n = 0
    with open(args.out, "w", encoding="utf-8") as f:
        for ex in iter_spider_samples(args.dev_json):
            if n >= args.limit:
                break

            schema = retrieve_schema_context(
                index_dir=args.bm25_index,
                question=ex["question"],
                db_id=ex["db_id"],
                topk_table=args.topk_table,
                topk_col=args.topk_col,
                topk_fk=args.topk_fk,
            )
            if args.schema_char_limit and len(schema) > args.schema_char_limit:
                schema = schema[:args.schema_char_limit]

            allowed_tables, allowed_cols = parse_allowed_from_schema(schema)

            prompt = PROMPT.format(
                schema=schema,
                allowed_tables=allowed_tables,
                allowed_cols=allowed_cols,
                question=ex["question"],
            )

            inp = tok(prompt, return_tensors="pt", truncation=True, max_length=512).to(device)

            # generate N candidates
            with torch.no_grad():
                outs = model.generate(
                    **inp,
                    max_new_tokens=args.max_new_tokens,
                    do_sample=False,
                    num_beams=max(args.num_candidates, 4),
                    num_return_sequences=args.num_candidates,
                    early_stopping=True,
                )

            cands_raw = [tok.decode(o, skip_special_tokens=True) for o in outs]
            cands_sql = [extract_sql(t) for t in cands_raw]

            db_path = default_db_path(args.db_root, ex["db_id"])

            exec_infos: List[Dict[str, Any]] = []
            for sql in cands_sql:
                ok, err, rows = _sqlite_exec_with_timeout(db_path, sql, timeout_s=args.timeout, max_rows=args.max_rows)
                exec_infos.append({"ok": ok, "err": err, "rows": rows})

            # baseline best by simple heuristic
            def score(info: Dict[str, Any]) -> float:
                if info["ok"]:
                    # prefer non-empty but don’t over-penalize empty (some correct queries return 0)
                    return 100.0 + (10.0 if info["rows"] > 0 else 0.0) - min(info["rows"], args.max_rows) * 0.01
                return 0.0

            best_i = max(range(len(exec_infos)), key=lambda i: score(exec_infos[i]))
            pred_sql = cands_sql[best_i].strip()
            chosen_reason = f"egs_best_{best_i}"

            # aggressive repair: ALWAYS ask reasoner for best SQL, using feedback
            repair_traces: List[Dict[str, Any]] = []
            last_error = "(none)"
            for r in range(args.repair_rounds):
                cands_block = format_candidates_for_repair(cands_sql, exec_infos)
                repair_prompt = REPAIR_AGGRESSIVE_PROMPT.format(
                    schema=schema,
                    allowed_tables=allowed_tables,
                    allowed_cols=allowed_cols,
                    question=ex["question"],
                    cands_block=cands_block,
                    last_error=last_error,
                )
                try:
                    cand = call_chat_api(
                        prompt=repair_prompt,
                        api_key=args.api_key,
                        model=args.repair_model,
                        base_url=args.base_url,
                        temperature=0.0,
                    )
                    fixed_sql = extract_sql(cand)

                    ok2, err2, rows2 = _sqlite_exec_with_timeout(
                        db_path, fixed_sql, timeout_s=args.timeout, max_rows=args.max_rows
                    )

                    repair_traces.append({
                        "round": r,
                        "proposal": fixed_sql,
                        "ok": ok2,
                        "err": err2,
                        "rows": rows2,
                    })

                    if ok2:
                        pred_sql = fixed_sql
                        chosen_reason = f"aggressive_repair_ok_r{r}"
                        break
                    else:
                        last_error = err2 or "unknown_error"
                except Exception as e:
                    repair_traces.append({"round": r, "exception": str(e)})
                    break

            rec = {
                "db_id": ex["db_id"],
                "question": ex["question"],
                "gold": ex["query"],
                "pred": pred_sql,
                "pred_meta": {
                    "chosen_reason": chosen_reason,
                    "db_path": db_path,
                    "candidates": cands_sql,
                    "exec_infos": exec_infos,
                    "repair_traces": repair_traces,
                },
            }
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")
            n += 1
            print(f"[{n}/{args.limit}] db={ex['db_id']} reason={chosen_reason} pred_len={len(pred_sql)}")

    print("[OK] wrote:", args.out)


if __name__ == "__main__":
    main()